### ISSUE TITLE
Remapeamento dos cards.

### ISSUE THREAD

**Issue by GustavoSantoz** [jv-farias/frontend-day-app#29]
Foi feita uma proposta de design de novos cards, de modo que fique mais agradável para o usuário. 

As propostas feitas.
![image](https://github.com/jv-farias/frontend-day-app/assets/74427958/37fa42ce-b571-4522-8838-43cef4f6ff67)

**Comment by jv-farias** [comment]
Boa noite! Desculpa o horário. Vou mandar como ficou os cards após as alterações que eu realizei tanto nos cards dos palestrantes ao vivo, quanto nos cards dos palestrantes na seção do cronograma das trilhas. 
Antes de fazer essas novas alterações, procurei falar com uma pessoa especialista que podia me ajudar.

**Segue o Layout abaixo:**

----

### Cards Cronogramas
![Cards do Cronograma das Trilhas](https://github.com/jv-farias/frontend-day-app/assets/84153149/6b2d6105-5303-4127-8389-6cde6aa4e15f)

----
### Cards Palestrantes Ao Vivo
![Cards Palestrantes Ao Vivo](https://github.com/jv-farias/frontend-day-app/assets/84153149/b4cf497c-0bdc-4e5f-a8da-8aa1c21f5ecf)

**Comment by GustavoSantoz** [comment]
Ótimo trabalho, João Vitor! O design ficou excelente e realçou bem as informações.
