### ISSUE TITLE
Desenvolver Protótipo no Figma

### ISSUE THREAD

**Issue by GustavoSantoz** [jv-farias/frontend-day-app#4]
# Sendo trabalhado o [Protótipo](https://www.figma.com/file/vuXQGRG1J7TbwBtAKFVMKa/Front-End-Day?type=design&node-id=0%3A1&mode=design&t=jdWE2x4SVpBDERk4-1) no Figma
- Foi colocado todo os design e ideias.
- Cada uma delas sofreu alterações.
- Sendo feito o design final

**Comment by RodrigoNet0** [comment]
# Importante
- Começar a desenvolver o código após a confirmação de todos no figma.
- Já fiz a review por minha parte, Aprovado.

**Comment by GustavoSantoz** [comment]
# Figma checado 🔧
Foi feito a revisão de todo o Figma com a presença de todos os colaboradores, discutido algumas ideias e suas implementações.
