### ISSUE TITLE
Implementar Scroll Automático para o Palestrante ao Vivo no Cronograma

### ISSUE THREAD

**Issue by RodrigoNet0** [jv-farias/frontend-day-app#45]
# **Descrição da Nova Funcionalidade:**
Estamos planejando implementar uma funcionalidade empolgante no projeto, que permitirá que os usuários ao entrarem no cronograma sejam automaticamente levados à seção que exibe o palestrante que está ao vivo no momento, de acordo com o horário.

## **Detalhes da Funcionalidade:**
- Quando os usuários acessarem o cronograma, a página identificará o horário atual.
- Com base no horário atual, a página fará automaticamente o scroll para a seção que contém o palestrante ao vivo.
- Isso proporcionará aos usuários uma experiência mais fluida e facilitará a localização do conteúdo atual.

### **Benefícios Esperados:**
- Melhoria na usabilidade do cronograma.
- Redução da necessidade de rolagem manual para encontrar o palestrante atual.

### **Passos Sugeridos para Implementação:**
1. Identificar o horário atual do usuário no momento em que ele acessa o cronograma.
2. Mapear o horário atual para a seção correspondente no cronograma.
3. Aplicar uma animação de scroll suave para levar o usuário até a seção correta.

**Informações Adicionais:**
- Certifique-se de realizar testes extensivos para garantir que a funcionalidade funcione corretamente em diferentes fusos horários e horários do dia.

**Comment by GustavoSantoz** [comment]
De acordo com o tempo disponível foi julgado que não vai ser possível ser implementado essa ideia no projeto.
