### ISSUE TITLE
[mobile]: Melhorar disposição do botão salvar/remover

### ISSUE THREAD

**Issue by AbraaoAlves** [jv-farias/frontend-day-app#67]
## mobile

| atual | proposta |
|-------|-----------|
|<img src="https://github.com/jv-farias/frontend-day-app/assets/608731/36ee3eaa-58a4-4a11-8449-c88bcdba56e7" height="300" />  |<img src="https://github.com/jv-farias/frontend-day-app/assets/608731/5cc91c77-ad94-408c-b672-83f4638d813c" height="300" />|

### Tasks

- [x] Remover a tag `p` com conteudo repedito @frontendday2023 para todos os cards
- [x] Aumentar a fonte do horario para o mesmo tamanho do topico de pausas

**Comment by GustavoSantoz** [comment]
Show, gostei muito da ideia do novo card apoio a implentação.
