### ISSUE TITLE
Animação com JS

### ISSUE THREAD

**Issue by GustavoSantoz** [jv-farias/frontend-day-app#7]

**Comment by RodrigoNet0** [comment]
# Pesquisar animações em CSS
### exemplos abaixo
- transition: transform 0.3s ease; ( Adiciona uma transição suave de 0.3 segundos)
-  transform: scale(1.2);  (Aplica um aumento de escala (zoom) quando o mouse passar por cima )

**Comment by RodrigoNet0** [comment]
# JavaScript
- Carrossel em Js
- Outro para construção do card
- Outro para Tópicos
