### ISSUE TITLE
QR Code

### ISSUE THREAD

**Issue by GustavoSantoz** [jv-farias/frontend-day-app#8]
Ao Final do projeto, criação do QRCode para link.

**Comment by Gustavo-S-Nascimento** [comment]
Fechando a issue por um tempo indeterminado, caso chegue ao final do projeto e dê tempo essa issue irá ser reaberta.

**Comment by GustavoSantoz** [comment]
Fechando a issue por um tempo indeterminado, caso chegue ao final do projeto e dê tempo essa issue irá ser reaberta.
